### ISSUE TITLE
Misiing dev.js file in config folder

### ISSUE THREAD

**Issue by mkaustubh** [parnabghosh1004/Project-Website-avishkar#1]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './dev'
Require stack:
- D:\Web Dev\del\Project-Website-avishkar-main\config\keys.js
- D:\Web Dev\del\Project-Website-avishkar-main\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Web Dev\del\Project-Website-avishkar-main\config\keys.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Web Dev\del\Project-Website-avishkar-main\app.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Web Dev\\del\\Project-Website-avishkar-main\\config\\keys.js',
    'D:\\Web Dev\\del\\Project-Website-avishkar-main\\app.js'
  ]
}

**Comment by parnabghosh1004** [comment]
Bro do not ever try to push .env or config files in which some api-key or password of some APIs used to github. Create your own from the the site. And if you by mistake do this, then it is their in your git history so may be github will warn you at some point of time and it is available to anyone.

Services that used keys - 

- MongoDB Atlas
- Cloudinary
- JWT

Make a simple google search to get started with these :)

**Comment by mkaustubh** [comment]
Thanks for the help
